import type { Metadata } from 'next'
import CormorantGaramond from 'next/font/local';
import './globals.css'

const CG = CormorantGaramond({ src: "./assets/fonts/Cormorant Garamond/CormorantGaramond-Regular.ttf"})

export const metadata: Metadata = {
  title: 'LittleQueenPhotography',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${CG.className} w-full h-full bg-black`}>
        {children}
      </body>
    </html>
  )
}
